apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: leetcode-clone

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - redis-deployment.yaml
  - judge0-db-pvc.yaml
  - judge0-db-deployment.yaml
  - judge0-deployment.yaml
  - judge0-worker-deployment.yaml
  - django-deployment.yaml

commonLabels:
  app.kubernetes.io/name: leetcode-clone
  app.kubernetes.io/version: "1.0.0"
